// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPICAP.TechChallenge.Data;

namespace TPICAP.TechChallenge.Data.Migrations
{
    [DbContext(typeof(PeopleContext))]
    [Migration("20210403113952_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TPICAP.TechChallenge.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SalutationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalutationId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1952, 9, 27, 16, 38, 5, 704, DateTimeKind.Local).AddTicks(56),
                            FirstName = "Curtis",
                            LastName = "Rutherford",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1980, 4, 9, 1, 53, 15, 467, DateTimeKind.Local).AddTicks(3774),
                            FirstName = "Emmett",
                            LastName = "Murazik",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1984, 10, 2, 6, 5, 27, 654, DateTimeKind.Local).AddTicks(314),
                            FirstName = "Elvira",
                            LastName = "Turner",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1955, 8, 29, 15, 28, 29, 565, DateTimeKind.Local).AddTicks(8899),
                            FirstName = "Lela",
                            LastName = "Zemlak",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1983, 8, 20, 19, 29, 29, 338, DateTimeKind.Local).AddTicks(2262),
                            FirstName = "Angel",
                            LastName = "Rippin",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1955, 6, 7, 13, 45, 8, 667, DateTimeKind.Local).AddTicks(3909),
                            FirstName = "Dora",
                            LastName = "Yost",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1993, 7, 19, 6, 42, 49, 619, DateTimeKind.Local).AddTicks(4471),
                            FirstName = "Denise",
                            LastName = "Waters",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1984, 2, 4, 17, 30, 56, 796, DateTimeKind.Local).AddTicks(1495),
                            FirstName = "Frank",
                            LastName = "Runolfsson",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2000, 7, 31, 12, 2, 38, 280, DateTimeKind.Local).AddTicks(3214),
                            FirstName = "Phillip",
                            LastName = "Cronin",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1969, 5, 10, 9, 0, 19, 71, DateTimeKind.Local).AddTicks(4960),
                            FirstName = "Gladys",
                            LastName = "Fritsch",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1997, 7, 1, 14, 11, 4, 14, DateTimeKind.Local).AddTicks(6466),
                            FirstName = "Tony",
                            LastName = "Blick",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2000, 8, 19, 15, 35, 44, 917, DateTimeKind.Local).AddTicks(4066),
                            FirstName = "Joanna",
                            LastName = "Carter",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1995, 6, 19, 6, 56, 27, 13, DateTimeKind.Local).AddTicks(4082),
                            FirstName = "Irene",
                            LastName = "Runolfsson",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1986, 9, 9, 0, 17, 0, 583, DateTimeKind.Local).AddTicks(4466),
                            FirstName = "Muriel",
                            LastName = "Abernathy",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1990, 1, 14, 17, 55, 0, 909, DateTimeKind.Local).AddTicks(9520),
                            FirstName = "Bennie",
                            LastName = "Lehner",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1996, 10, 12, 6, 29, 39, 95, DateTimeKind.Local).AddTicks(4553),
                            FirstName = "Laurie",
                            LastName = "O'Hara",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1989, 9, 12, 14, 13, 33, 549, DateTimeKind.Local).AddTicks(539),
                            FirstName = "Olive",
                            LastName = "Purdy",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1952, 5, 26, 17, 47, 23, 461, DateTimeKind.Local).AddTicks(8085),
                            FirstName = "Seth",
                            LastName = "Krajcik",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1987, 7, 21, 1, 58, 50, 552, DateTimeKind.Local).AddTicks(6072),
                            FirstName = "Beverly",
                            LastName = "Dicki",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1997, 4, 14, 21, 44, 40, 161, DateTimeKind.Local).AddTicks(1183),
                            FirstName = "Claire",
                            LastName = "Greenfelder",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1988, 3, 30, 0, 17, 25, 226, DateTimeKind.Local).AddTicks(5543),
                            FirstName = "Moses",
                            LastName = "Hodkiewicz",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(1964, 2, 7, 2, 0, 14, 979, DateTimeKind.Local).AddTicks(6112),
                            FirstName = "Catherine",
                            LastName = "Graham",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1954, 10, 8, 23, 42, 45, 470, DateTimeKind.Local).AddTicks(4827),
                            FirstName = "Clifford",
                            LastName = "Senger",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1974, 12, 21, 2, 44, 1, 231, DateTimeKind.Local).AddTicks(4819),
                            FirstName = "Dave",
                            LastName = "Bernier",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1964, 1, 14, 19, 37, 45, 857, DateTimeKind.Local).AddTicks(5430),
                            FirstName = "Isabel",
                            LastName = "Mraz",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(1980, 6, 18, 3, 12, 6, 443, DateTimeKind.Local).AddTicks(9039),
                            FirstName = "Geoffrey",
                            LastName = "Lehner",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(1958, 7, 28, 5, 10, 53, 685, DateTimeKind.Local).AddTicks(7533),
                            FirstName = "Gertrude",
                            LastName = "Price",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(1963, 2, 11, 21, 15, 18, 573, DateTimeKind.Local).AddTicks(9173),
                            FirstName = "Emilio",
                            LastName = "Rath",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(2000, 11, 6, 4, 19, 14, 661, DateTimeKind.Local).AddTicks(8196),
                            FirstName = "Johnnie",
                            LastName = "Deckow",
                            SalutationId = 1
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(1963, 11, 23, 9, 50, 53, 88, DateTimeKind.Local).AddTicks(6732),
                            FirstName = "Shari",
                            LastName = "Gutkowski",
                            SalutationId = 1
                        });
                });

            modelBuilder.Entity("TPICAP.TechChallenge.Data.Entities.Salutation", b =>
                {
                    b.Property<int>("SalutationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SalutationName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SalutationId");

                    b.ToTable("Salutations");

                    b.HasData(
                        new
                        {
                            SalutationId = 1,
                            SalutationName = "Mr"
                        },
                        new
                        {
                            SalutationId = 2,
                            SalutationName = "Mrs"
                        },
                        new
                        {
                            SalutationId = 3,
                            SalutationName = "Miss"
                        },
                        new
                        {
                            SalutationId = 4,
                            SalutationName = "Dr"
                        },
                        new
                        {
                            SalutationId = 5,
                            SalutationName = "Sir"
                        },
                        new
                        {
                            SalutationId = 6,
                            SalutationName = "Lord"
                        },
                        new
                        {
                            SalutationId = 7,
                            SalutationName = "Lady"
                        },
                        new
                        {
                            SalutationId = 8,
                            SalutationName = "Prof"
                        });
                });

            modelBuilder.Entity("TPICAP.TechChallenge.Data.Entities.Person", b =>
                {
                    b.HasOne("TPICAP.TechChallenge.Data.Entities.Salutation", "Salutation")
                        .WithMany()
                        .HasForeignKey("SalutationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salutation");
                });
#pragma warning restore 612, 618
        }
    }
}
