apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: tpicapapi
        image: 786094074965.dkr.ecr.eu-west-2.amazonaws.com/tpicapapi:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080